title: ZeroToOne
description: Senior Software Engineer

url: https://0t1.me/
baseurl: ""
paginate_path: blog/page:num/
permalink: /blog/:categories/:year/:month/:day/:title

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Résumé
    url: https://github.com/mortymacs/resume/releases/download/latest/resume.pdf
  - title: Contact
    url: mailto:m@0t1.me
  - title: Appointment
    url: https://calendly.com/mortymacs/meet-mort

social:
  github: mortymacs
  twitter: mortymacs
  email: m@0t1.me
  linkedin: morteza-nourelahi-alamdari

#google_analytics: ""
google_web_stream: "G-DPJYQNN1X6"

disqus:
    shortname: 0t1-me
