# Site settings
title: Morteza Nourelahi Alamdari
email: me@mortezana.com
author: Morteza Nourelahi Alamdari
tagline: GNU/Linux Software Developer
description: >- # this means to ignore newlines until "baseurl:"
  GNU/Linux Software Developer
keywords: ["programmer", "programming", "developer", "code", "source", "python", "linux", "gnu", "c", "c++", "tools"]
baseurl: ""
url: "http://mortezana.com"
permalink: /posts/:categories/:title/
twitter_username: mortezaipo

# Build settings
markdown: kramdown

plugins: [jekyll-paginate]

paginate: 5
paginate_path: "/posts/page:num/"
